language: node_js
node_js:
  - "0.10"
install:
  - "sudo apt-get install cabal-install"
  - "cabal update"
  - "cabal install Cabal cabal-install"
  - "export PATH=~/.cabal/bin:$PATH"
  - "cabal install purescript-0.6.9.5 --force-reinstalls"
  - "npm install bower grunt-cli pulp -g"
  - "npm install"
  - "bower install"
  - "bower update"
script:
  - "pulp run"
